package integrationtest.generationgap.generatedbuilder;

public class StringPropertyBeanWithSomethingElseForGenerationGapTestBuilder extends integrationtest.generationgap.generatedbuilder.StringPropertyBeanWithSomethingElseForGenerationGapTestBaseBuilder<StringPropertyBeanWithSomethingElseForGenerationGapTestBuilder> {
    public static StringPropertyBeanWithSomethingElseForGenerationGapTestBuilder aStringPropertyBeanWithSomethingElseForGenerationGapTest() {
        return new StringPropertyBeanWithSomethingElseForGenerationGapTestBuilder();
    }
}
